services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - config/mariadb/.env
    volumes:
      - mariadb_data:/var/lib/mysql
  wormholesystems:
    build:
      context: .
      dockerfile: config/wormholesystems/Dockerfile
    restart: unless-stopped
    env_file:
      - config/wormholesystems/.env
    volumes:
      - ./wormhole-systems:/var/www/html
    depends_on:
      - database
  webserver:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "3000:80"
      - "3443:443"
    volumes:
      - ./wormhole-systems:/var/www/html
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/sites:/etc/nginx/conf.d
      - ./config/ssl:/etc/nginx/ssl
    depends_on:
        - wormholesystems
volumes:
  mariadb_data: